---
title: "Higher Education Historic Enrollment"
author: "Luis Barajas"
date: "2023-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Higher Education Historic Enrollment


```{r}
# Erase Everything 

rm(list = ls())

# Library

suppressMessages(library(dplyr))
suppressMessages(library(magrittr))
suppressMessages(library(readxl))
suppressMessages(library(openxlsx))
suppressMessages(library(ggplot2))
suppressMessages(library(tidyr))
suppressMessages(library(stringr))
suppressMessages(library(ggplot2))
suppressMessages(library(anytime))
suppressMessages(library(ggthemes))
suppressMessages(library(tidyverse))
suppressMessages(library(gganimate))
```


```{r, echo=FALSE}
# Reading the required data

mat_20002013 = read.xlsx("Matricula20002013.xlsx", startRow = 6)
mat_2014 = read.xlsx("Matricula2014.xlsx", startRow = 6)
mat_2015 = read.xlsx("Matricula2015.xlsx", startRow = 6)
mat_2016 = read.xlsx("Matricula2016.xlsx", startRow = 6)
mat_2017 = read.xlsx("Matricula2017.xlsx", startRow = 6)
mat_2018 = read.xlsx("Matricula2018.xlsx", startRow = 7)
mat_2019 = read.xlsx("Matricula2019.xlsx", startRow = 8)
mat_2020 = read.xlsx("Matricula2020.xlsx", startRow = 9)
mat_2021 = read.xlsx("Matricula2021.xlsx", startRow = 11)
mat_2022 = read.xlsx("Matricula2022.xlsx", startRow = 9)


```


```{r}
# Processing and standardizing databases

# 2000 - 2013

mat_20002013 %<>% select(-`Total.2000-1`,-`Total.2000-2`,
                         -`Total.2001-1`,-`Total.2001-2`,
                         -`Total.2002-1`,-`Total.2002-2`,
                         -`Total.2003-1`,-`Total.2003-2`,
                         -`Total.2004-1`,-`Total.2004-2`,
                         -`Total.2005-1`,-`Total.2005-2`,
                         -`Total.2006-1`,-`Total.2006-2`,
                         -`Total.2007-1`,-`Total.2007-2`,
                         -`Total.2008-1`,-`Total.2008-2`,
                         -`Total.2009-1`,-`Total.2009-2`,
                         -`Total.2010-1`,-`Total.2010-2`,
                         -`Total.2011-1`,-`Total.2011-2`,
                         -`Total.2012-1`,-`Total.2012-2`,
                         -`Total.2013-1`,-`Total.2013-2`)

mat_20002013 %<>% mutate(NIVEL_ACADEMICO = if_else(Nivel.de.Formación == "DOCTORADO" | Nivel.de.Formación == "ESPECIALIZACION" | Nivel.de.Formación == "MAESTRIA", "POSGRADO", "PREGRADO"))

mat_20002013 %<>% pivot_longer(cols = `Hombre.2000-1`:`Mujer.2013-2`, names_to = "A", values_to = "TOTAL_MATRICULA")

mat_20002013 %<>% separate(A, into =c("SEXO", "AÑO", "SEMESTRE"), sep = "[.-]")


# 2000 - 2013

mat_20002013 %<>% select(CODIGO_IES = Código.de.la.Institución, IES_PADRE = Código.de.la.Institución, IES = `Institución.de.Educación.Superior.(IES)`, SECTOR = Sector.IES, CARACTER = Carácter.IES, COD_DPTO_IES = `Código.del.departamento.(IES)`, DPTO_IES = Departamento.de.domicilio.de.la.IES, 
                                   COD_MUN_IES =`Código.del.Municipio.(IES)`, MUN_IES = Municipio.de.domicilio.de.la.IES,CODIGO_SNIES_PROGRAMA=Código.SNIES.del.programa, PROGRAMA =Programa.Académico, NIVEL_ACADEMICO, NIVEL_FORMACION = Nivel.de.Formación, METODOLOGIA = Metodología.del.programa, AREA_CONOCIMIENTO = Área.de.Conocimiento, NBC = `Núcleo.Básico.del.Conocimiento.(NBC)`, COD_DPTO_PROGRAMA = `Código.del.Departamento.(Programa)`,
                                   DPTO_PROGRAMA = Departamento.de.oferta.del.programa, COD_MUN_PROGRAMA = `Código.del.Municipio.(Programa)`, MUN_PROGRAMA = Municipio.de.oferta.del.programa,SEXO,AÑO,SEMESTRE,`TOTAL_MATRICULA`)

IES = mat_20002013 %>% filter(CODIGO_IES != 9110 & SEMESTRE == 1)
SENA = mat_20002013 %>% filter(CODIGO_IES == 9110 & SEMESTRE == 2)
mat_esta_20002013 = rbind(IES,SENA)
rm(mat_20002013, IES, SENA)

# 2014/2021-----------------------------

mat_2014 %<>% select(CODIGO_IES = Código.de.la.Institución, everything())

mat_estadistica <- function(basematricula){
  IES = basematricula %>% filter(CODIGO_IES != 9110 & Semestre == 1 )
  SENA = basematricula %>% filter(CODIGO_IES == 9110 & Semestre == 2 )
  baseestadistica = rbind(IES, SENA)
  return(baseestadistica)
}

# 2014

mat_esta_2014 = mat_estadistica(mat_2014)
rm(mat_2014)

mat_esta_2014 %<>% select(CODIGO_IES, IES_PADRE = IES.PADRE, IES = `Institución.de.Educación.Superior.(IES)`, SECTOR = Sector.IES, CARACTER = Caracter.IES,
                          COD_DPTO_IES = `Código.del.departamento.(IES)`, DPTO_IES = Departamento.de.domicilio.de.la.IES, COD_MUN_IES = `Código.del.Municipio.(IES)`, MUN_IES = Municipio.de.domicilio.de.la.IES, CODIGO_SNIES_PROGRAMA = Código.SNIES.del.programa, 
                          PROGRAMA = Programa.Académico, NIVEL_ACADEMICO = Nivel.Académico,
                          NIVEL_FORMACION = Nivel.de.Formación, METODOLOGIA = Metodología,
                          AREA_CONOCIMIENTO = Área.de.Conocimiento, NBC = `Núcleo.Básico.del.Conocimiento.(NBC)`, COD_DPTO_PROGRAMA = `Código.del.Departamento.(Programa)`,
                          DPTO_PROGRAMA = Departamento.de.oferta.del.programa, COD_MUN_PROGRAMA = `Código.del.Municipio.(Programa)`, MUN_PROGRAMA = Municipio.de.oferta.del.programa,
                          SEXO = Género, AÑO = Año, SEMESTRE = Semestre, TOTAL_MATRICULA = Matriculados.2014)

# 2015

mat_2015 %<>% select(CODIGO_IES = Código.de.la.Institución, everything())

mat_esta_2015 = mat_estadistica(mat_2015)
rm(mat_2015)

mat_esta_2015 %<>% select(CODIGO_IES, IES_PADRE = IES.PADRE, IES = `Institución.de.Educación.Superior.(IES)`, SECTOR = Sector.IES, CARACTER = Caracter.IES,
                          COD_DPTO_IES = `Código.del.departamento.(IES)`, DPTO_IES = Departamento.de.domicilio.de.la.IES, COD_MUN_IES = `Código.del.Municipio.(IES)`, MUN_IES = Municipio.de.domicilio.de.la.IES, CODIGO_SNIES_PROGRAMA = Código.SNIES.del.programa, 
                          PROGRAMA = Programa.Académico, NIVEL_ACADEMICO = Nivel.Académico,
                          NIVEL_FORMACION = Nivel.de.Formación, METODOLOGIA = Metodología,
                          AREA_CONOCIMIENTO = Área.de.Conocimiento, NBC = `Núcleo.Básico.del.Conocimiento.(NBC)`, COD_DPTO_PROGRAMA = `Código.del.Departamento.(Programa)`,
                          DPTO_PROGRAMA = Departamento.de.oferta.del.programa, COD_MUN_PROGRAMA = `Código.del.Municipio.(Programa)`, MUN_PROGRAMA = Municipio.de.oferta.del.programa,
                          SEXO = Género, AÑO = Año, SEMESTRE = Semestre, TOTAL_MATRICULA = Matriculados.2015)

# 2016

mat_2016 %<>% select(CODIGO_IES = Código.de.la.Institución, everything())

mat_esta_2016 = mat_estadistica(mat_2016)
rm(mat_2016)

mat_esta_2016 %<>% select(CODIGO_IES, IES_PADRE = IES.PADRE, IES = `Institución.de.Educación.Superior.(IES)`, SECTOR = Sector.IES, CARACTER = Caracter.IES,
                          COD_DPTO_IES = `Código.del.departamento.(IES)`, DPTO_IES = Departamento.de.domicilio.de.la.IES, COD_MUN_IES = `Código.del.Municipio.(IES)`, MUN_IES = Municipio.de.domicilio.de.la.IES, CODIGO_SNIES_PROGRAMA = Código.SNIES.del.programa, 
                          PROGRAMA = Programa.Académico, NIVEL_ACADEMICO = Nivel.Académico,
                          NIVEL_FORMACION = Nivel.de.Formación, METODOLOGIA = Metodología,
                          AREA_CONOCIMIENTO = Área.de.Conocimiento, NBC = `Núcleo.Básico.del.Conocimiento.(NBC)`, COD_DPTO_PROGRAMA = `Código.del.Departamento.(Programa)`,
                          DPTO_PROGRAMA = Departamento.de.oferta.del.programa, COD_MUN_PROGRAMA = `Código.del.Municipio.(Programa)`, MUN_PROGRAMA = Municipio.de.oferta.del.programa,
                          SEXO= Sexo, AÑO = Año, SEMESTRE = Semestre, TOTAL_MATRICULA = Matriculados.2016)

# 2017

mat_2017 %<>% select(CODIGO_IES = Código.de.la.Institución, everything())

mat_esta_2017 = mat_estadistica(mat_2017)
rm(mat_2017)

mat_esta_2017 %<>% select(CODIGO_IES, IES_PADRE = IES.PADRE, IES = `Institución.de.Educación.Superior.(IES)`, SECTOR = Sector.IES, CARACTER = Caracter.IES,
                          COD_DPTO_IES = `Código.del.departamento.(IES)`, DPTO_IES = Departamento.de.domicilio.de.la.IES, COD_MUN_IES = `Código.del.Municipio.(IES)`, MUN_IES = Municipio.de.domicilio.de.la.IES, CODIGO_SNIES_PROGRAMA = Código.SNIES.del.programa, 
                          PROGRAMA = Programa.Académico, NIVEL_ACADEMICO = Nivel.Académico,
                          NIVEL_FORMACION = Nivel.de.Formación, METODOLOGIA = Metodología,
                          AREA_CONOCIMIENTO = Área.de.Conocimiento, NBC = `Núcleo.Básico.del.Conocimiento.(NBC)`, COD_DPTO_PROGRAMA = `Código.del.Departamento.(Programa)`,
                          DPTO_PROGRAMA = Departamento.de.oferta.del.programa, COD_MUN_PROGRAMA = `Código.del.Municipio.(Programa)`, MUN_PROGRAMA = Municipio.de.oferta.del.programa,
                          SEXO = Sexo, AÑO = Año, SEMESTRE = Semestre, TOTAL_MATRICULA = Matriculados.2017)

# 2018

mat_2018 %<>% select(CODIGO_IES = Código.de.la.Institución, everything())

mat_esta_2018 = mat_estadistica(mat_2018)
rm(mat_2018)

mat_esta_2018 %<>% select(CODIGO_IES, IES_PADRE = IES.PADRE, IES = `Institución.de.Educación.Superior.(IES)`, SECTOR = Sector.IES, CARACTER = Caracter.IES,
                          COD_DPTO_IES = `Código.del.departamento.(IES)`, DPTO_IES = Departamento.de.domicilio.de.la.IES, COD_MUN_IES = `Código.del.Municipio.(IES)`, MUN_IES = Municipio.de.domicilio.de.la.IES, CODIGO_SNIES_PROGRAMA = Código.SNIES.del.programa, 
                          PROGRAMA = Programa.Académico, NIVEL_ACADEMICO = Nivel.Académico,
                          NIVEL_FORMACION = Nivel.de.Formación, METODOLOGIA = Metodología,
                          AREA_CONOCIMIENTO = Área.de.Conocimiento, NBC = `Núcleo.Básico.del.Conocimiento.(NBC)`, COD_DPTO_PROGRAMA = `Código.del.Departamento.(Programa)`,
                          DPTO_PROGRAMA = Departamento.de.oferta.del.programa, COD_MUN_PROGRAMA = `Código.del.Municipio.(Programa)`, MUN_PROGRAMA = Municipio.de.oferta.del.programa,
                          SEXO = Sexo, AÑO = Año, SEMESTRE = Semestre, TOTAL_MATRICULA = Matriculados.2018)

# 2019

mat_2019 %<>% select(CODIGO_IES = CÓDIGO.DE.LA.INSTITUCIÓN, Semestre = SEMESTRE, everything())

mat_esta_2019 = mat_estadistica(mat_2019)
rm(mat_2019)

mat_esta_2019 %<>% select(CODIGO_IES, IES_PADRE = IES_PADRE, IES = `INSTITUCIÓN.DE.EDUCACIÓN.SUPERIOR.(IES)`, SECTOR = SECTOR.IES, CARACTER = CARACTER.IES,
                          COD_DPTO_IES = `CÓDIGO.DEL.DEPARTAMENTO.(IES)`, DPTO_IES = DEPARTAMENTO.DE.DOMICILIO.DE.LA.IES, COD_MUN_IES = CÓDIGO.DEL.MUNICIPIO, MUN_IES = MUNICIPIO.DE.DOMICILIO.DE.LA.IES, CODIGO_SNIES_PROGRAMA = CÓDIGO.SNIES.DEL.PROGRAMA, 
                          PROGRAMA = PROGRAMA.ACADÉMICO, NIVEL_ACADEMICO = NIVEL.ACADÉMICO,
                          NIVEL_FORMACION = NIVEL.DE.FORMACIÓN, METODOLOGIA = METODOLOGÍA,
                          AREA_CONOCIMIENTO = ÁREA.DE.CONOCIMIENTO, NBC = `NÚCLEO.BÁSICO.DEL.CONOCIMIENTO.(NBC)`, COD_DPTO_PROGRAMA = `CÓDIGO.DEL.DEPARTAMENTO.(PROGRAMA)`,
                          DPTO_PROGRAMA = DEPARTAMENTO.DE.OFERTA.DEL.PROGRAMA, COD_MUN_PROGRAMA = `CÓDIGO.DEL.MUNICIPIO.(PROGRAMA)`, MUN_PROGRAMA = MUNICIPIO.DE.OFERTA.DEL.PROGRAMA,
                          SEXO = SEXO, AÑO = AÑO, SEMESTRE = Semestre, TOTAL_MATRICULA = MATRICULADOS)

# 2020 

mat_2020 %<>% select(CODIGO_IES = CÓDIGO.DE.LA.INSTITUCIÓN, Semestre = SEMESTRE, everything())

mat_esta_2020 = mat_estadistica(mat_2020)
rm(mat_2020)

mat_esta_2020 %<>% select(CODIGO_IES, IES_PADRE = IES_PADRE, IES = `INSTITUCIÓN.DE.EDUCACIÓN.SUPERIOR.(IES)`, SECTOR = SECTOR.IES, CARACTER = CARACTER.IES,
                          COD_DPTO_IES = `CÓDIGO.DEL.DEPARTAMENTO.(IES)`, DPTO_IES = DEPARTAMENTO.DE.DOMICILIO.DE.LA.IES, COD_MUN_IES = `CÓDIGO.DEL.MUNICIPIO.(IES)`, MUN_IES = MUNICIPIO.DE.DOMICILIO.DE.LA.IES, CODIGO_SNIES_PROGRAMA = CÓDIGO.SNIES.DEL.PROGRAMA, 
                          PROGRAMA = PROGRAMA.ACADÉMICO, NIVEL_ACADEMICO = NIVEL.ACADÉMICO,
                          NIVEL_FORMACION = NIVEL.DE.FORMACIÓN, METODOLOGIA = METODOLOGÍA,
                          AREA_CONOCIMIENTO = ÁREA.DE.CONOCIMIENTO, NBC = `NÚCLEO.BÁSICO.DEL.CONOCIMIENTO.(NBC)`, COD_DPTO_PROGRAMA = `CÓDIGO.DEL.DEPARTAMENTO.(PROGRAMA)`,
                          DPTO_PROGRAMA = DEPARTAMENTO.DE.OFERTA.DEL.PROGRAMA, COD_MUN_PROGRAMA = `CÓDIGO.DEL.MUNICIPIO.(PROGRAMA)`, MUN_PROGRAMA = MUNICIPIO.DE.OFERTA.DEL.PROGRAMA,
                          SEXO = SEXO, AÑO = AÑO, SEMESTRE = Semestre, TOTAL_MATRICULA = MATRICULADOS)

# 2021

mat_2021 %<>% select(CODIGO_IES = CÓDIGO.DE.LA.INSTITUCIÓN, Semestre = SEMESTRE, everything())

mat_esta_2021 = mat_estadistica(mat_2021)
rm(mat_2021)


mat_esta_2021 %<>% select(CODIGO_IES, IES_PADRE = IES_PADRE, IES = `INSTITUCIÓN.DE.EDUCACIÓN.SUPERIOR.(IES)`, SECTOR = SECTOR.IES, CARACTER = CARACTER.IES,
                          COD_DPTO_IES = `CÓDIGO.DEL.DEPARTAMENTO.(IES)`, DPTO_IES = DEPARTAMENTO.DE.DOMICILIO.DE.LA.IES, COD_MUN_IES = `CÓDIGO.DEL.MUNICIPIO.(IES)`, MUN_IES = MUNICIPIO.DE.DOMICILIO.DE.LA.IES, CODIGO_SNIES_PROGRAMA = CÓDIGO.SNIES.DEL.PROGRAMA, 
                          PROGRAMA = PROGRAMA.ACADÉMICO, NIVEL_ACADEMICO = NIVEL.ACADÉMICO,
                          NIVEL_FORMACION = NIVEL.DE.FORMACIÓN, METODOLOGIA = METODOLOGÍA,
                          AREA_CONOCIMIENTO = ÁREA.DE.CONOCIMIENTO, NBC = `NÚCLEO.BÁSICO.DEL.CONOCIMIENTO.(NBC)`, COD_DPTO_PROGRAMA = `CÓDIGO.DEL.DEPARTAMENTO.(PROGRAMA)`,
                          DPTO_PROGRAMA = DEPARTAMENTO.DE.OFERTA.DEL.PROGRAMA, COD_MUN_PROGRAMA = `CÓDIGO.DEL.MUNICIPIO.(PROGRAMA)`, MUN_PROGRAMA = MUNICIPIO.DE.OFERTA.DEL.PROGRAMA,
                          SEXO = SEXO, AÑO = AÑO, SEMESTRE = Semestre, TOTAL_MATRICULA = MATRICULADOS)


# 2022

mat_2022 %<>% select(CODIGO_IES = CÓDIGO.DE.LA.INSTITUCIÓN, Semestre = SEMESTRE, everything())

mat_esta_2022 = mat_estadistica(mat_2022)
rm(mat_2022)


mat_esta_2022 %<>% select(CODIGO_IES, IES_PADRE = IES_PADRE, IES = `INSTITUCIÓN.DE.EDUCACIÓN.SUPERIOR.(IES)`, SECTOR = SECTOR.IES, CARACTER = CARACTER.IES,
                          COD_DPTO_IES = `CÓDIGO.DEL.DEPARTAMENTO.(IES)`, DPTO_IES = DEPARTAMENTO.DE.DOMICILIO.DE.LA.IES, COD_MUN_IES = `CÓDIGO.DEL.MUNICIPIO.(IES)`, MUN_IES = MUNICIPIO.DE.DOMICILIO.DE.LA.IES, CODIGO_SNIES_PROGRAMA = CÓDIGO.SNIES.DEL.PROGRAMA, 
                          PROGRAMA = PROGRAMA.ACADÉMICO, NIVEL_ACADEMICO = NIVEL.ACADÉMICO,
                          NIVEL_FORMACION = NIVEL.DE.FORMACIÓN, METODOLOGIA = METODOLOGÍA,
                          AREA_CONOCIMIENTO = ÁREA.DE.CONOCIMIENTO, NBC = `NÚCLEO.BÁSICO.DEL.CONOCIMIENTO.(NBC)`, COD_DPTO_PROGRAMA = `CÓDIGO.DEL.DEPARTAMENTO.(PROGRAMA)`,
                          DPTO_PROGRAMA = DEPARTAMENTO.DE.OFERTA.DEL.PROGRAMA, COD_MUN_PROGRAMA = `CÓDIGO.DEL.MUNICIPIO.(PROGRAMA)`, MUN_PROGRAMA = MUNICIPIO.DE.OFERTA.DEL.PROGRAMA,
                          SEXO = SEXO, AÑO = AÑO, SEMESTRE = Semestre, TOTAL_MATRICULA = MATRICULADOS)




mat_esta_20142021 = rbind(mat_esta_2014, mat_esta_2015, mat_esta_2016, mat_esta_2017,
                            mat_esta_2018, mat_esta_2019, mat_esta_2020, mat_esta_2021, mat_esta_2022)

rm(mat_esta_2014, mat_esta_2015, mat_esta_2016, mat_esta_2017,
                            mat_esta_2018, mat_esta_2019, mat_esta_2020, mat_esta_2021, mat_esta_2022)



Historico_Matricula_ES = rbind(mat_esta_20002013, mat_esta_20142021)
rm(mat_esta_20002013, mat_esta_20142021)

```

```{r}
# Unifying characters

Historico_Matricula_ES %<>% mutate_if(is.character, toupper)
Historico_Matricula_ES %<>% mutate_if(is.character, ~gsub("[Á]", "A", .x, ignore.case = TRUE))
Historico_Matricula_ES %<>% mutate_if(is.character, ~gsub("[É]", "E", .x, ignore.case = TRUE))
Historico_Matricula_ES %<>% mutate_if(is.character, ~gsub("[Í]", "I", .x, ignore.case = TRUE))
Historico_Matricula_ES %<>% mutate_if(is.character, ~gsub("[Ó]", "O", .x, ignore.case = TRUE))
Historico_Matricula_ES %<>% mutate_if(is.character, ~gsub("[Ú]", "U", .x, ignore.case = TRUE))

# SEXO
table(Historico_Matricula_ES$SEXO)
Historico_Matricula_ES$SEXO %<>% str_replace_all("FEMENINO", "MUJER")
Historico_Matricula_ES$SEXO %<>% str_replace_all("MASCULINO", "HOMBRE")

# NIVEL DE FORMACION

table(Historico_Matricula_ES$NIVEL_FORMACION)
Historico_Matricula_ES$NIVEL_FORMACION %<>% str_replace_all("UNIVERSITARIA", "UNIVERSITARIO")

```
## First Plot enrollment by Sector

```{r}

Sector = Historico_Matricula_ES  %>% group_by(AÑO, SECTOR) %>% summarise(Total_Matricula = sum(TOTAL_MATRICULA)) %>% ungroup()

Sector %<>% filter(AÑO > 2001)
Sector$AÑO %<>% anydate()
Sector %<>% mutate(AÑO = if_else(AÑO =="2002-01-01", anydate("2002-08-07"), AÑO))
Sector %<>% mutate(AÑO = if_else(AÑO =="2021-01-01", anydate("2021-12-31"), AÑO))


nombres = c("Alvaro Uribe 1","Alvaro Uribe 2", "Juan M. Santos 1","Juan M. Santos 2", "Iván Duque")
comienzo = as.Date(c("2002-08-07", "2006-08-07", "2010-08-07","2014-08-07","2018-08-07"))
final = c(comienzo[-1], as.Date("2021-12-31"))
gob <- c("Alvaro Uribe", "Alvaro Uribe", "Juan M. Santos", "Juan M. Santos", "Ivan Duque")

presidentes <- data.frame(nombres, comienzo, final, gob, stringsAsFactors=F)
presidentes$gob %<>% factor(levels=c("Alvaro Uribe","Juan M. Santos", "Ivan Duque"))

ggplot(Sector) + geom_line(aes(x=AÑO, y=Total_Matricula, group = SECTOR, colour = SECTOR)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1))

yrng <- range(Sector$Total_Matricula, na.rm=TRUE)
xrng <- range(Sector$AÑO, na.rm=TRUE)

matplot = ggplot(Sector) + geom_line(aes(x=AÑO, y=Total_Matricula, group = SECTOR, colour = SECTOR)) + 
  scale_color_manual(values = c("#450c54","#22908b"))+ geom_rect(data = presidentes, 
            aes(xmin = comienzo, xmax=final,
                fill = gob), 
            ymin=yrng[1]-1000000, ymax=yrng[2]+1000000) + scale_fill_manual(values = alpha(c("purple","green", "blue"), 0.2)) + geom_vline(data=presidentes, aes(xintercept=as.numeric(comienzo)),
    color="grey50", linetype=5, size=0.5) +labs(title="Matrícula Histórica en Educación Superior por Sector",
        y = "Total matrícula", 
        caption = c("Fuente: Ministerio de Educación Nacional - Colombia", "Elaboración: @luchobarajas_"),
        colour ="") +
  theme(panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 18),
        legend.position = "bottom",
        plot.title = element_text(hjust = 0.5, size =20),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust=c(0,1), size = 14),axis.text = element_text(size = 14), 
        legend.text = element_text(size = 12)) +
  geom_text(aes(x= anydate("2002-08-07"), label="\nÁlvaro Uribe 1", y=1100000), colour="#9575CD", angle=90, size = 4)+
  geom_text(aes(x= anydate("2006-08-07"), label="\nÁlvaro Uribe 2", y=1100000), colour="#9575CD", angle=90, size = 4)+
  geom_text(aes(x= anydate("2010-08-07"), label="\nJuan M.Santos 1", y=500000), colour="#009688", angle=90, size = 4)+
  geom_text(aes(x= anydate("2014-08-07"), label="\nJuan M.Santos 2 - Ser Pilo Paga", y=590000), colour="#009688", angle=90, size = 4)+
  geom_text(aes(x= anydate("2018-08-07"), label="\nIván Duque - Generación E", y=570000), colour="#3F51B5", angle=90, size = 4) + guides(fill = "none") 

matplot
  
ggsave("Histórico Matrícula.png", matplot, width = 12, height = 7)




```

## Second Plot knowlege area
```{r}
table(Historico_Matricula_ES$AREA_CONOCIMIENTO)

# Unifying characters

Historico_Matricula_ES$AREA_CONOCIMIENTO %<>% str_replace("AGRONOMIA VETERINARIA Y AFINES", "AGRONOMIA, VETERINARIA Y AFINES")
Historico_Matricula_ES$AREA_CONOCIMIENTO %<>% str_replace("ECONOMIA ADMINISTRACION CONTADURIA Y AFINES", "ECONOMIA, ADMINISTRACION, CONTADURIA Y AFINES")
Historico_Matricula_ES$AREA_CONOCIMIENTO %<>% str_replace("INGENIERIA ARQUITECTURA URBANISMO Y AFINES", "INGENIERIA, ARQUITECTURA, URBANISMO Y AFINES")
Historico_Matricula_ES$AREA_CONOCIMIENTO %<>% tolower()


capitalize_first_word <- function(text) {
  lower<- str_to_lower(text)
  words <- strsplit(lower, " ")[[1]]
  words[1] <- str_to_title(words[1])
  return(paste(words, collapse = " "))
}


Historico_Matricula_ES$AREA_CONOCIMIENTO <- sapply(Historico_Matricula_ES$AREA_CONOCIMIENTO, capitalize_first_word)


AREA= Historico_Matricula_ES %>% filter(NIVEL_ACADEMICO == "PREGRADO") %>% group_by(AREA_CONOCIMIENTO,AÑO) %>% 
  summarise(TotalMat = sum(TOTAL_MATRICULA)) %>% ungroup() %>% filter(AREA_CONOCIMIENTO != "Sin clasificar")
AREA$AÑO %<>% as.numeric()
AREA%<>% group_by(AÑO) %<>% mutate(share =( TotalMat/sum(TotalMat))*100) 

AREA %<>% select(Área = AREA_CONOCIMIENTO, everything())

AREA$Área <-  fct_rev(AREA$Área)

AREA <- AREA %>%
  mutate(Área = fct_reorder(Área, desc(-share)))

AREA_plot = ggplot(data = AREA,aes(x= AÑO, y=share, fill = Área)) + 
  geom_col()+
  geom_text(aes(label = paste0(round(share ), "%")), 
            position = position_stack(vjust = 0.5), 
            size = 2)+
labs(title="Composición histórica de la matrícula en educación superior en Colombia",
     subtitle = "Nivel académico: Pregrado",
        y = "Participación por área del conocimiento", 
        caption = c("Fuente: Ministerio de Educación Nacional - Colombia", "Elaboración: @luchobarajas_"),
        colour ="") + scale_fill_manual(values = c("#ad1457","#f44336","#ff9800","#ffc107","#8bc34a" ,"#009688","#1565c0","#448aff"))+
  theme(panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 18),
        legend.position = "bottom",
        plot.title = element_text(hjust = 0.5, size =20),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust=c(0,1), size = 14),axis.text = element_text(size = 14), 
        legend.text = element_text(size = 12)) 

ggsave("Área Histórico.png", AREA_plot, width = 13, height = 7)
```

## Second Plot Basic core of knowledge

```{r}
# Unifying characters

Historico_Matricula_ES$NBC %<>% str_replace_all(",","")
Historico_Matricula_ES$NBC %<>% str_replace_all("ANTROPOLOGIA ARTES LIBERALES","ANTROPOLOGIA Y  ARTES LIBERALES")
Historico_Matricula_ES$NBC %<>% str_replace_all("ANTROPOLOGIA Y  ARTES LIBERALES", "ANTROPOLOGIA Y ARTES LIBERALES")
Historico_Matricula_ES$NBC %<>% str_replace_all("ATES PLASTICAS VISUALES Y AFINES", "ARTES PLASTICAS VISUALES Y AFINES")
Historico_Matricula_ES$NBC %<>% str_replace_all("BIBLIOTECOLOGIA OTROS DE CIENCIAS SOCIALES Y HUMANAS", "BIBLIOTECOLOGIA Y OTROS DE CIENCIAS SOCIALES Y HUMANAS")
Historico_Matricula_ES$NBC %<>% str_replace_all("CIENCIA POLITICA RELACIONES INTERNACIONALES", "CIENCIA POLITICA Y RELACIONES INTERNACIONALES")
Historico_Matricula_ES$NBC %<>% str_replace_all("DISENIO", "DISEÑO")
Historico_Matricula_ES$NBC %<>% str_replace_all("IINGENIERIA INDUSTRIAL ALIMENTOS Y AFINES", "INGENIERIA AGROINDUSTRIAL ALIMENTOS Y AFINES")
Historico_Matricula_ES$NBC %<>% str_replace_all("INGENIERIA ADMNISTRATIVA Y AFINES","INGENIERIA ADMINISTRATIVA Y AFINES")
Historico_Matricula_ES$NBC %<>% str_replace_all("OPTOMETRIA OTROS PROGRAMAS DE CIENCIAS DE LA SALUD","OPTOMETRIA Y OTROS PROGRAMAS DE CIENCIAS DE LA SALUD")

Historico_Matricula_ES$NBC <- sapply(Historico_Matricula_ES$NBC, capitalize_first_word)

NBC = Historico_Matricula_ES %>% filter(NIVEL_ACADEMICO == "PREGRADO") %>%
  group_by(AREA_CONOCIMIENTO,NBC,AÑO) %>% 
  summarise(TotalMat = sum(TOTAL_MATRICULA)) %>% 
  ungroup() %>% 
  filter(NBC != "Sin clasificar")

NBC$AÑO %<>% as.numeric()
NBC%<>% group_by(AÑO, AREA_CONOCIMIENTO) %<>% mutate(share =( TotalMat/sum(TotalMat))*100) 

#--- EAC
EAC = NBC %>% filter(AREA_CONOCIMIENTO == "Economia, administracion, contaduria y afines")
EAC$NBC<- fct_rev(EAC$NBC)


EAC_plot = ggplot(data = EAC,aes(x= AÑO, y=share, fill = NBC)) + 
  geom_col()+
  geom_text(aes(label = paste0(round(share ), "%")), 
            position = position_stack(vjust = 0.5), 
            size = 2)+
labs(title="Composición histórica de la matrícula NBC Economía, administración y contaduría",
     subtitle = "Nivel académico: Pregrado",
        y = "Participación por NBC", 
        caption = c("Fuente: Ministerio de Educación Nacional - Colombia", "Elaboración: @luchobarajas_"),
        colour ="") +
  scale_fill_manual(values = c("#DBEFED","#08cad1","#1A81D1"))+
  theme(panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 18),
        legend.position = "bottom",
        plot.title = element_text(hjust = 0.5, size =20),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust=c(0,1), size = 14),axis.text = element_text(size = 14), 
        legend.text = element_text(size = 12))


ggsave("EAC Histórico.png", EAC_plot, width = 12, height = 7)

```


```{r}
#--- Ciencias Sociales 

NBC = Historico_Matricula_ES %>% filter(NIVEL_ACADEMICO == "PREGRADO") 

NBC %<>% mutate(NBC = if_else(NBC== "Antropologia y artes liberales"|
                                    NBC== "Bibliotecologia y otros de ciencias sociales y humanas"|
                                    NBC== "Lenguas modernas literatura linguistica y afines"|
                                    NBC== "Geografia historia"|
                                    NBC == "Formacion relacionada con el campo militar o policial" |
                                    NBC == "Filosofia teologia y afines", 
                                    "Otros de ciencias sociales y humanas", NBC))

NBC %<>% group_by(AREA_CONOCIMIENTO,NBC,AÑO) %>% 
  summarise(TotalMat = sum(TOTAL_MATRICULA)) %>% 
  ungroup() %>% 
  filter(NBC != "Sin clasificar")

NBC$AÑO %<>% as.numeric()

Csociales = NBC %>% filter(AREA_CONOCIMIENTO == "Ciencias sociales y humanas")
Csociales %<>% group_by(AÑO, AREA_CONOCIMIENTO) %<>% 
  mutate(share =( TotalMat/sum(TotalMat))*100) 


Csociales <- Csociales %>%
  mutate(NBC = fct_reorder(NBC, desc(-share)))



Cs_plot = ggplot(data = Csociales,aes(x= AÑO, y=share, fill = NBC)) + 
  geom_col()+
  geom_text(aes(label = paste0(round(share ), "%")), 
            position = position_stack(vjust = 0.5), 
            size = 2)+  scale_fill_manual(values = c("#fb8500","#fd9e02", "#ffb703", "#f0efeb","#126782","#219ebc","#8ecae6"))+
labs(title="Composición histórica de la matrícula NBC Ciencias Sociales",
     subtitle = "Nivel académico: Pregrado",
        y = "Participación por NBC", 
        caption = c("Fuente: Ministerio de Educación Nacional - Colombia", "Elaboración: @luchobarajas_"),
        colour ="") +
  theme(panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 18),
        legend.position = "right",
        plot.title = element_text(hjust = 0.5, size =20),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust=c(0,1), size = 14),axis.text = element_text(size = 14), 
        legend.text = element_text(size = 12))

ggsave("CS Histórico.png", Cs_plot, width = 12, height = 7)
```


```{r}
#---Ingenierías

NBC = Historico_Matricula_ES %>% filter(NIVEL_ACADEMICO == "PREGRADO") 

NBC %<>% mutate(NBC = if_else(NBC == "Ingenieria administrativa y afines"|
                              NBC == "Ingenieria admnistrativa y afines"|
                              NBC == "Ingenieria agricola forestal y afines"|
                              NBC == "Ingenieria de minas metalurgia y afines"|
                              NBC == "Ingenieria biomedica y afines"|
                              NBC == "Ingenieria agronomica pecuaria y afines"|
                              NBC == "Ingenieria quimica y afines", 
                                    "Otras ingenierias", NBC))
NBC %<>% group_by(AREA_CONOCIMIENTO,NBC,AÑO) %>% 
  summarise(TotalMat = sum(TOTAL_MATRICULA)) %>% 
  ungroup() %>% 
  filter(NBC != "Sin clasificar")

NBC$AÑO %<>% as.numeric()

Ing = NBC %>% filter(AREA_CONOCIMIENTO == "Ingenieria, arquitectura, urbanismo y afines")
Ing %<>% group_by(AÑO, AREA_CONOCIMIENTO) %<>% 
  mutate(share =( TotalMat/sum(TotalMat))*100) 

Ing <- Ing %>%
  mutate(NBC = fct_reorder(NBC, desc(-share)))

Ing_plot = ggplot(data = Ing,aes(x= AÑO, y=share, fill = NBC)) + 
  geom_col()+
  geom_text(aes(label = paste0(round(share ), "%")), 
            position = position_stack(vjust = 0.5), 
            size = 2) + scale_fill_manual(values = c("#54478c","#2c699a","#048ba8","#0db39e","#16db93", "#83e377", "#b9e769","#efea5a","#f1c453","#f29e4c"))+
labs(title="Composición histórica de la matrícula NBC Ingeniería, arquitectura, urbanismo y afines",
     subtitle = "Nivel académico: Pregrado",
        y = "Participación por NBC", 
        caption = c("Fuente: Ministerio de Educación Nacional - Colombia", "Elaboración: @luchobarajas_"),
        colour ="") +
  theme(panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 18),
        legend.position = "right",
        plot.title = element_text(hjust = -0.5, size =20),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust=c(0,1), size = 14),axis.text = element_text(size = 14), 
        legend.text = element_text(size = 12)) 


ggsave("Ing Histórico.png", Ing_plot, width = 12, height = 7)
```

```{r}

AREA_Gen = Historico_Matricula_ES %>% filter(NIVEL_ACADEMICO == "PREGRADO"& AÑO > 2011) %>% group_by(AREA_CONOCIMIENTO,AÑO, SEXO) %>% 
  summarise(TotalMat = sum(TOTAL_MATRICULA)) %>% ungroup() %>% filter(AREA_CONOCIMIENTO != "Sin clasificar")
AREA_Gen$AÑO %<>% as.numeric()
AREA_Gen%<>% group_by(AÑO,SEXO) %<>% mutate(share =( TotalMat/sum(TotalMat))*100) 

AREA_Gen %<>% select(Área = AREA_CONOCIMIENTO, everything())

AREA_Gen %<>% mutate(SEXO = if_else(SEXO== "HOMBRE", "Hombre", "Mujer"))

AREA_Gen <- AREA_Gen %>%
  mutate(Área = fct_reorder(Área, desc(-share)))

AREA_Gen_plot = ggplot(data = AREA_Gen,aes(x= AÑO, y=share, fill = Área)) + 
  geom_col()+
  geom_text(aes(label = paste0(round(share ), "%")), 
            position = position_stack(vjust = 0.5), 
            size = 2)+
labs(title="Composición histórica de la matrícula en educación superior en Colombia por Sexo",
     subtitle = "Nivel académico: Pregrado",
        y = "Participación por área del conocimiento", 
        caption = c("Fuente: Ministerio de Educación Nacional - Colombia", "Elaboración: @luchobarajas_"),
        colour ="") + scale_fill_manual(values = c("#ad1457","#f44336","#ff9800","#ffc107","#8bc34a" ,"#009688","#1565c0","#448aff"))+
  theme(panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 18),
        legend.position = "bottom",
        plot.title = element_text(hjust = 0.5, size =20),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust=c(0,1), size = 14),axis.text = element_text(size = 14), 
        legend.text = element_text(size = 12)) + facet_wrap(vars(SEXO))

ggsave("Area gen Histórico.png", AREA_Gen_plot , width = 12, height = 7)
```

